Hw 16.1
Tarabarnik/internet-shop pull request #7
Opened 2019-09-22 10:50 UTC by Tarabarnik

2019-09-22 10:55 UTC, Tarabarnik commented
Видалив InjectorOld, але Injector новий не працює

2019-09-23 12:24 UTC, boroda4436 commented
. class

2019-09-24 10:52 UTC, boroda4436 requested changes

2019-09-24 10:52 UTC, boroda4436 commented on .gitignore
>  .target/*
```suggestion
target/*
```
Ось тут в тебе помилка)

2019-09-24 12:40 UTC, boroda4436 approved these changes

2019-09-24 12:43 UTC, merged